### ISSUE TITLE
Comment post promise not resolving

### ISSUE THREAD

**Issue by stuartpb** [trevorsenior/snoocore#122]
See https://github.com/stuartpb/QIKlaxonBot/blob/master/lib/klaxons/postKlaxonReply.js#L9, which is called from https://github.com/stuartpb/QIKlaxonBot/blob/master/bot.js#L73 after refreshing via https://github.com/stuartpb/QIKlaxonBot/blob/master/bot.js#L32.

Line 9 is definitely getting reached, but line 16 isn't, and I can't figure out why.

**Comment by stuartpb** [comment]
I updated to 2.8.0 and re-pushed it and it suddenly resolved, but that appears to have been a fluke.

It's possible that this may be a sporadic issue with the API server right now, but if that were the case, wouldn't the request at least time out?

**Comment by stuartpb** [comment]
Also, I tried this with a different promise and it did resolve, so the issue is definitely not in the handling of the promise.

**Comment by stuartpb** [comment]
It looks like this might have been related to the refreshToken being bad in some way - I re-authenticated, and now it's working as intended.

**Comment by trevorsenior** [comment]
I'll check out your code later today and see what I can find out.

**Comment by stuartpb** [comment]
Seeing as how this problem went away when I replaced the refreshToken, I think it's more likely that the bug lies somewhere in Snoocore's code (and/or Reddit's API implementation).

My working theory is that I made the initial auth request when Reddit was still going through all the OAuth transition stuff, and so something was up with their implementation where the data associated with that auth token was incomplete/corrupt, causing the API server to not respond to authenticated requests. (Which is strange, since it seems like that would cause a 50X response from the CloudFlare layer, but maybe OAuth isn't behind CloudFlare.)

Does Snoocore's Node request function have a timeout for its requests?

**Comment by trevorsenior** [comment]
> Does Snoocore's Node request function have a timeout for its requests?

There isn't a timeout. It will hang until reddit comes back with a response (2xx or 5xx).

I only experience what you were going through when revoking access from an application using the reddit website *or* calling `reddit.deauth` with a refresh token (but I don't think you're doing this). Basically anything that will invalidate the refresh token can cause this. It seems like this will be hard to reproduce if it fixed itself by replacing the refresh token. :confused: 

Why are you using `web` OAuth for the bot? You may be able to avoid funky refresh tokens invalidating using `script` based OAuth. I only poked around your bot briefly trying to locate the config, but it's using your module ['envigor'](https://github.com/stuartpb/envigor). I can't really figure out the structure in the short time I have. I'll check it out later though!

**Comment by stuartpb** [comment]
The config isn't in the codebase - it's specified at runtime in envronment variables as part of the production system, [the way all proper Twelve-Factor apps do configuration](http://12factor.net/config). The envigor module just takes environment variables like `REDDIT_APP_SECRET ` and puts them into an object like `cfg.reddit.secret`.

If you want to test with your own mock up implementation of the app, you can use the credentials of a test app you've created at https://www.reddit.com/prefs/apps/, then run the app (if on a local machine using something like https://ngrok.com/ to have a public-addressable API callback domain) with an environment like this (assuming you have Redis and RethinkDB installed and running in their default configurations):

```bash
REDIS_SERVICE=default \
REDDIT_APP_ID=<insert app ID here> \
REDDIT_APP_SECRET=<insert app secret here> \
CANONICAL_HOST=<insert domain for auth callbacks here> \
REDDIT_USERNAME=<insert bot account's name here> \
node server.js --bot
```

> Why are you using web OAuth for the bot?

(A) [Because it's a web app](https://qiklaxonbot.redditbots.com), and (B) because non-delegated credentials like "script based OAuth" defeat the entire purpose of OAuth tokens (there's no point in giving someone a restricted key when you're letting them change the locks).

**Comment by stuartpb** [comment]
I just checked my server and it looks like, while not responding, Reddit does eventually hang up:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at TLSSocket.socketOnEnd (_http_client.js:300:23)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

This is why you use a timeout. Why is Snoocore implementing its own request framework using the core HTTP module for Node, anyway? There's a reason virtually every Node project that makes HTTP requests uses [request](https://github.com/request/request).

**Comment by stuartpb** [comment]
The documentation around `refresh_token` is kind of spotty. Do refresh tokens have some kind of limit around being used multiple times during the duration of the last access granted with the refresh token (the way this app will when deployed repeatedly)?

**Comment by trevorsenior** [comment]
A lot of reddit OAuth implementations are a bit hacky / deviate from the spec. Sticking with web does make sense in your case. I do appreciate all the feedback you're giving me -- I personally haven't worked with a long running *web* OAuth bot using the library so everything you update me on is very helpful.

> The config isn't in the codebase - it's specified at runtime in environment variables as part of the production system, the way all proper Twelve-Factor apps do configuration.

I'm guilty of embedding of `process.env.ENV_VAR` inside my test config code, but at least I move them to environment variables I suppose. I'll give that article a read & check out your module. Seems like an interesting read.

> Why is Snoocore trying to roll its own request framework using the core HTTP module for Node, anyway?

This may be something to re-evaluate in the future, but it all came down to cross environment issues supporting Node.js and Browser JavaScript. This library started using [superagent](https://github.com/visionmedia/superagent) for awhile, but it could not handle file uploads and some other edge cases if I recall correctly. It has been a year though, a lot could have changed.

> it's not infeasible that an issue like a network partition or an implementation glitch (like the one Reddit appears to have right now) could cause Reddit to become unresponsive

Thanks for bringing it up. What would be a good default timeout for this? I don't think reddit calls take that long on average, so maybe a minute? Of course it would be configurable in the settings.

As for implementation of the timeout for requests, I was thinking about retrying a request again if it times out. It would use a retry attempt for that call. This will prevent additional error handling that a developer would have to handle. 

> Do refresh tokens have some kind of limit around being used multiple times during the duration of the last access granted with the refresh token (the way this app will when deployed repeatedly)?

That's probably a question for /r/redditdev -- It would be easy enough to hammer a refresh token for new access tokens and see if anything happens I suppose.

**Comment by trevorsenior** [comment]
> I just checked my server and it looks like, ~~while not responding, Reddit does eventually hang up, a little over 12 hours later~~ (actually, I just checked the DB and it looks like this happened as part of a request during normal operation)
 
I wish wasn't coming up on finals week. I don't mind running your setup and getting down and dirty with the problem. I'll have a bit of free time this Thursday evening when I can sit down and diagnose this further. I plan on releasing the 3.x.x branch of this library in the next few days as well... maybe an upgrade ([if it isn't too painful](http://snoocore.readme.io/v3.0.0/docs/migration-guide)) may solve the issue (with the timeout of requests implemented).

**Comment by stuartpb** [comment]
> I do appreciate all the feedback you're giving me -- I personally haven't worked with a long running web OAuth bot using the library so everything you update me on is very helpful.

That kind of shows in the way Snoocore does contexts, which doesn't make a lot of sense for web apps (only one user at a time etc) - the way QIKlaxonBot deals with it is kind of hacky (eg. for auth requests, it initializes a whole new Snoocore instance for every request). I can file a separate issue describing the model/flow that would make more sense if you're open to it for 3.0.0.

> I'm guilty of embedding of process.env.ENV_VAR inside my test config code, but at least I move them to environment variables I suppose. I'll give that article a read & check out your module. Seems like an interesting read.

If you mean that you use `process.env.ENV_VAR` to access variables, there's nothing really wrong with that - the main purpose of envigor is to abstract away configurations that use different environment variables so your app doesn't have to do logic like [this][email.js] to support multiple third-party service providers / implementations. (See also: the decomposition of [the non-standard Redis URL format][redis.js] for use with node-redis.)

[email.js]: https://github.com/stuartpb/envigor/blob/master/lib/cfg/email.js
[redis.js]: https://github.com/stuartpb/envigor/blob/master/lib/cfg/redis.js

> This may be something to re-evaluate in the future, but it all came down to cross environment issues supporting Node.js and Browser JavaScript. This library started using superagent for awhile, but it could not handle file uploads and some other edge cases if I recall correctly. It has been a year though, a lot could have changed.

Yeah, [superagent is pretty bad][1]. It's always been the Pepsi to `request`'s Coke, as long as I've known Node, and the disparity has only gotten more dire since tj did his exit for Go.

As far as cross-platform solutions go, the one I would suggest would be to target the [Fetch Standard][fetch], which is natively supported in (IIRC) the latest stable release of Chrome, can be supported in the rest of browsers using [GitHub's polyfill for it][github/fetch], and can be supported in node using [node-fetch][].

[1]: https://twitter.com/stuartpb/status/574057422559428608
[fetch]: https://fetch.spec.whatwg.org/
[github/fetch]: https://github.com/github/fetch
[node-fetch]: https://github.com/bitinn/node-fetch

> Thanks for bringing it up. What would be a good default timeout for this? I don't think reddit calls take that long on average, so maybe a minute? Of course it would be configurable in the settings.

Heroku considers a request timed out after [30 seconds](https://devcenter.heroku.com/articles/limits#router), and in my opinion / experience with reddit's API even that is pretty gratuitous. I would set the default as whatever time limit Reddit uses for the "we took too long to make that page for you" response - from memory, I'd say that's after about 10 seconds (though it's probably worth looking up in https://github.com/reddit/reddit or asking /u/alienth).

(Also, it's worth noting here that [the fetch spec has not come to a conclusion on how timeouts should be handled, or even how requests should be cancelled][fetch-20].)

[fetch-20]: https://github.com/whatwg/fetch/issues/20

> As for implementation of the timeout for requests, I was thinking about retrying a request again if it times out. It would use a retry attempt for that call. This will prevent additional error handling that a developer would have to handle.

I don't recommend that. *Maybe* provide an `err.retry` function on the request that timed out, but in general, when something goes wrong with a request, the caller should be notified and given control of the situation. (See also: the socket hangup I posted about above.)

**Comment by trevorsenior** [comment]
> I can file a separate issue describing the model/flow that would make more sense if you're open to it for 3.0.0.

You seem to know a lot about the model/flow of things. If it's not too much trouble I'd love to discuss it as a new feature for the 3.x.x version of the library. 

I've thought about this before, but didn't really get any feedback on it -- https://github.com/trevorsenior/snoocore/issues/94#issuecomment-76660688

Feel free to comment in there, or open a new issue for a possible new model/flow for web OAuth.

> Fetch Standard

Ah, I did read about that awhile back. I'll take a closer look at it.

> I don't recommend that. Maybe provide an err.retry function on the request that timed out, but in general, when something goes wrong with a request, the caller should be notified and given control of the situation. 

In your case I suppose [setting `retryAttempts: 0`](http://snoocore.readme.io/v2.0.0/docs/configuration#retry-attempts) will make it always error when any request fails vs. retrying the endpoint.

It only came to mind because I've had several issues from users with reddit's common 5xx errors throwing off bots. After awhile I added in the retry logic for better or worse. For newcomers it does simplify the library usage a bit. I know at some point in the future someone else will open an issue requesting timeouts to be handled the same way / "retry" the endpoint on a timeout.

**Comment by trevorsenior** [comment]
I had a fellow on reddit waiting for the 3.0.0 release last week that asked about it yesterday (They needed the Application only OAuth support). As it was basically done I went ahead and made it the current version.

I threw in the timeout logic in the 3.0.0 release. Snoocore will kill any request that takes longer than 20 seconds. It will throw an [Error](http://snoocore.readme.io/v3.0.0/docs/errors#responseerror) that will have some information about the request that didn't go through. 

This may fix your problem (not the hacky bit of using new Snoocore instances), though it will require some configuration updates, I think in your case just:

```
consumerKey → key
consumerSecret → secret
```

**Comment by stuartpb** [comment]
Okay - I'll propose my model as a prospective base for 4.0.0.

**Comment by trevorsenior** [comment]
I look forward to reading the model proposal. 

- - -

As for the fiddling of initial setup variables (*sorry!*)
 
The major version bump was an opportunity to fine tune certain aspects on the library. Removing  `reddit.raw`, or keeping the `login: { user/pass }` option was another thing that could have technically stayed for backwards compatibility, but it would have just been extra code to maintain. Removing code, test cases, and keeping things simple was the goal in this major release as they come once in a blue moon.

The good news is that Snoocore strictly follows semver. You can rest assured that breaking changes will only happen in major versions. This major 3.0.0 release has been in development for months, and version 2.x.x has been the current one for about a year. 

Again, sorry for the futz with something as minor as `consumerKey` → `key`. <sup>(don't hate me)</sup>

**Comment by stuartpb** [comment]
I'm going to post a new issue in a little bit with my ideas for 4.0.0 - I can also push a PR later for the init back/sidecompat.
